// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/jmgilman/cue-playground/cli/pkg/schema

package schema

#Schema: {
	field1: string     @go(Field1)
	field2: int        @go(Field2)
	field3: bool       @go(Field3)
	sub?:   #SubSchema @go(Sub)
}

#SubSchema: {
	field1: string @go(Field1)
}
